#!/bin/sh

set -e

T=`mktemp -d /tmp/pdflatexfilter.XXXXXX`

cat /dev/stdin | sed "s_PDFLATEXFILTERD_${T}_g" > $T/a.tex

latexmk -pdf -pdflatex="pdflatex -shell-escape -interaction nonstopmode -output-directory=$T" -outdir=$T -auxdir=$T $T/a >$T/oo 2>$T/oe || cat $T/oo >&2

cat $T/a.pdf

rm -rf $T
